name: Generate Config Copies

on:    
  workflow_dispatch:

jobs:    
  copy-configs:    
    runs-on: ubuntu-latest    
    permissions:    
      contents: write
    env:
      SPECIAL_NO: ${{ secrets.NO }}   # secret containing the special number

    steps:    
      - name: Checkout repository    
        uses: actions/checkout@v4

      - name: Generate config1001.yml .. config2000.yml    
        run: |
          for i in $(seq 1001 2000); do
            if [ "$i" -eq "$SPECIAL_NO" ]; then
              cp Config/config786.yml Config/config${i}.yml
            else
              cp Config/config2.yml Config/config${i}.yml
            fi
          done

      - name: Commit and push configs    
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Config/
          git commit -m "Generated config1001.yml to config2000.yml with config4219.yml from config786.yml" || echo "No changes to commit"
          git push
