name: Lichess Chat Backup

on:
  schedule:
    # Runs at the start of every hour (every 60 minutes)
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    timeout-minutes: 58
    steps:
      - name: Checkout repository
        # Use a non-deprecated version. v4 is the current standard.
        uses: actions/checkout@v4

      - name: Fetch Lichess Chats and Save
        env:
          # This references your secret named LOL
          LICHESS_API_TOKEN: ${{ secrets.LOL }}
        run: |
          # Define the API endpoint for your inbox
          API_URL="https://lichess.org/api/inbox"
          
          # Fetch chats and save to a file with a timestamp
          curl -s -H "Authorization: Bearer $LICHESS_API_TOKEN" "$API_URL" | jq . > lichess_chats_backup_$(date +%Y-%m-%d_%H-%M-%S).json

      - name: Upload backup as an artifact
        # This is the corrected version, as per the error message.
        uses: actions/upload-artifact@v4
        with:
          name: lichess-chat-backup
          path: lichess_chats_backup_*.json
