name: Lichess Chat Backup

on:
  schedule:
    # Runs at the start of every hour (every 60 minutes)
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    timeout-minutes: 58  # Job will be cancelled after 58 minutes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Lichess Chats and Save
        env:
          LICHESS_API_TOKEN: ${{ secrets.LOL }}
        run: |
          # Define the API endpoint for your inbox
          API_URL="https://lichess.org/api/inbox"
          
          # Fetch chats and append to a file with a timestamp
          curl -s -H "Authorization: Bearer $LICHESS_API_TOKEN" "$API_URL" | jq . >> lichess_chats_backup_$(date +%Y-%m-%d_%H-%M-%S).json

      - name: Upload backup as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: lichess-chat-backup
          path: lichess_chats_backup_*.json
