name: Sync mew with Torom/main

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/Torom/<repo-name>.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Rebase my mew branch onto upstream/main
        run: |
          git checkout mew
          git rebase upstream/main || git rebase --abort

      - name: Push changes
        run: git push origin mew --force-with-lease
