name: Sync Upstream BotLi into master branch

on:
  schedule:
    - cron: '0 0 * * *'   # every day at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/Torom/BotLi.git || true
          git fetch upstream --prune

      - name: Update side branch master from upstream/master
        run: |
          # checkout (or create) the local master branch
          git checkout master || git checkout -b master
          # sync it to upstream/master
          git reset --hard upstream/master

      - name: Push updated master to fork
        run: |
          git push origin master --force-with-lease
